"""empty message

Revision ID: 30219be946f1
Revises: e09f9faa6d30
Create Date: 2021-04-13 20:42:05.473484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30219be946f1'
down_revision = 'e09f9faa6d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
