"""empty message

Revision ID: e09f9faa6d30
Revises: 9d7aab6d2e9b
Create Date: 2021-04-13 01:24:02.720823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09f9faa6d30'
down_revision = '9d7aab6d2e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.drop_constraint('users_user_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_email_key', 'users', ['user_email'])
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
